### ISSUE TITLE
deprecate our TranslatableExtension if SonataTranslationBundle is finished

### ISSUE THREAD

**Issue by dbu** [symfony-cmf/CoreBundle#130]
there is https://github.com/sonata-project/SonataTranslationBundle which does the translatable a lot better than we do. once there is a stable release, we should deprecate https://github.com/symfony-cmf/CoreBundle/blob/master/Admin/Extension/TranslatableExtension.php in favor of that bundle.

**Comment by ConneXNL** [comment]
A 1.0.0 version of SonataTranslationBundle was released in March, according to Packagist.
