### ISSUE TITLE
Error message when missing ODM config options not clear

### ISSUE THREAD

**Issue by EdwardIII** [symfony-cmf/CoreBundle#156]
When adding Symfony CMF to an existing project if the ODM config is missed out the error isn't very clear. Running any command produces this error:

  [Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]                           
  You have requested a non-existent parameter "None of the managerParameters resulted in a valid name".  

This is the required config addition:

        doctrine_phpcr:
            odm:
                auto_mapping: true
                auto_generate_proxy_classes: "%kernel.debug%"
            ...

Would something like "ODM config not found" make more sense?

Thanks to @lsmith77 for pointing this out on #symfony-cmf

**Comment by dbu** [comment]
https://github.com/symfony/symfony/pull/15501
