### ISSUE TITLE
Add VersionableInterface

### ISSUE THREAD

**Issue by hason** [symfony-cmf/CoreBundle#178]

**Comment by lsmith77** [comment]
what does this relate to?

**Comment by dbu** [comment]
there is versioning support in phpcr-odm http://doctrine-phpcr-odm.readthedocs.org/en/latest/reference/versioning.html

@hason what do you miss? what would you need a VersionableInterface for?

**Comment by WouterJ** [comment]
Ping @hason, can you please add some more explanation to this issue?
